name: icontheory
favicon: null
layout_spectrum: 0.3194
typography_spectrum: 0.56083
title: icontheory
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#3f1c54'
    - '#cbcbcb'
    - '#f89c1d'
    - '#cc4527'
  brandStrength: 0.75
  lightness: 0.8806302670855075
  saturation: 0.6164758813101798
  rhythmicContrast: 0.2024463010020554
purpose: []
